//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_supp
    {
        public int ID { get; set; }
        public string supp_name { get; set; }
        public string supp_phone { get; set; }
        public string supp_email { get; set; }
    }
}
